# Generated by Django 5.2.11 on 2026-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.IntegerField()),
                ('Password', models.CharField(max_length=250)),
            ],
        ),
    ]
