# Generated by Django 5.2.11 on 2026-03-18 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.artisan'),
        ),
    ]
