# Generated by Django 5.2.11 on 2026-03-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phonenumber', models.CharField(max_length=15)),
                ('Orderid', models.CharField(max_length=50)),
                ('Productname', models.CharField(max_length=100)),
                ('Issue_type', models.CharField(max_length=100)),
                ('Product_image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('Description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
