# Generated by Django 5.2.11 on 2026-03-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
